### ISSUE TITLE
Chart Y-Axis doesn't start from 0 for timeToInitialDisplay

### ISSUE THREAD

**Issue by AfzalivE** [theapache64/benchart#12]
Noticed maybe an unintentional (?) issue in chart where `timeToInitialDisplay` y-axis doesn't start from 0, leading to a slightly misleading graph.

For example in this case.

<img width="450" alt="Screenshot 2023-03-20 at 4 42 31 PM" src="https://user-images.githubusercontent.com/436057/226461560-1ab39485-eb29-4317-a612-672f39031603.png">

**Comment by theapache64** [comment]
See #13 for explanation
